apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homework-app.fullname" . }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
data:
  index.html: |
    {{ .Files.Get "../files/index.html" | indent 4 }}
  geolocation.html: |
    {{ .Files.Get "../files/geolocation.html" | indent 4 }}
